// next
import type { Metadata } from "next";
// mui + styles
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@/utils/context/ThemeContext";
import { CssBaseline } from "@mui/material";
import { yekan, geistSans, geistMono } from "@/styles/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Card-Tak",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${yekan.variable} ${geistSans.variable} ${geistMono.variable}`}
      >
        <AppRouterCacheProvider>
          <ThemeProvider>
            <CssBaseline />
            {children}
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
